import { CareCircleMember, CalendarEvent, Vault, LogEntry, FeedPost, PatientInfo, Visit, Notification, VaultDocument, WellnessDay } from '@/types'

// Patient: Grandma Margaret
export const demoPatient: PatientInfo = {
  name: 'Margaret Johnson',
  dateOfBirth: new Date('1942-06-15'),
  roomNumber: '214B',
  facilityName: 'Sunrise Skilled Nursing Facility',
  facilityPhone: '(555) 800-1234',
  facilityAddress: '450 Sunrise Blvd, Salt Lake City, UT 84103',
  admissionDate: new Date('2025-11-01'),
  primaryDiagnosis: 'Post hip replacement recovery',
}

// Family + Staff members
export const demoMembers: CareCircleMember[] = [
  {
    id: '1',
    name: 'Sarah Johnson',
    email: 'sarah@example.com',
    phone: '(555) 123-4567',
    role: 'admin',
    relationship: 'Daughter',
    joinedAt: new Date('2025-11-01'),
  },
  {
    id: '2',
    name: 'Michael Johnson',
    email: 'michael@example.com',
    phone: '(555) 234-5678',
    role: 'family',
    relationship: 'Son',
    joinedAt: new Date('2025-11-02'),
  },
  {
    id: '3',
    name: 'Emily Davis',
    email: 'emily@example.com',
    phone: '(555) 345-6789',
    role: 'family',
    relationship: 'Granddaughter',
    joinedAt: new Date('2025-11-05'),
  },
  {
    id: 'n1',
    name: 'Nurse Rachel Kim',
    email: 'rachel.kim@sunrise-snf.com',
    phone: '(555) 800-1235',
    role: 'nurse',
    relationship: 'Primary Nurse',
    joinedAt: new Date('2025-11-01'),
  },
  {
    id: 'n2',
    name: 'CNA David Torres',
    email: 'david.torres@sunrise-snf.com',
    phone: '(555) 800-1236',
    role: 'nurse',
    relationship: 'CNA',
    joinedAt: new Date('2025-11-01'),
  },
]

const today = new Date()
const yesterday = new Date(today.getTime() - 1 * 24 * 60 * 60 * 1000)
const twoDaysAgo = new Date(today.getTime() - 2 * 24 * 60 * 60 * 1000)
const threeDaysAgo = new Date(today.getTime() - 3 * 24 * 60 * 60 * 1000)
const inTwoDays = new Date(today.getTime() + 2 * 24 * 60 * 60 * 1000)
const inFourDays = new Date(today.getTime() + 4 * 24 * 60 * 60 * 1000)
const nextWeek = new Date(today.getTime() + 7 * 24 * 60 * 60 * 1000)

export const demoEvents: CalendarEvent[] = [
  {
    id: '1',
    title: 'Orthopedic Follow-up',
    description: 'Post-surgery hip check with Dr. Williams',
    type: 'doctor_visit',
    date: inTwoDays,
    time: '10:00 AM',
    location: 'On-site clinic, Room 102',
    patientMood: 'good',
    createdBy: 'n1',
    createdAt: new Date(),
  },
  {
    id: '2',
    title: 'Physical Therapy Session',
    description: 'Hip mobility exercises and gait training',
    type: 'therapy_session',
    date: today,
    time: '2:00 PM',
    endTime: '3:00 PM',
    location: 'PT Room, 1st Floor',
    patientMood: 'fair',
    createdBy: 'n1',
    createdAt: new Date(),
  },
  {
    id: '3',
    title: 'Bingo & Social Hour',
    description: 'Weekly community activity in the recreation room',
    type: 'facility_event',
    date: inFourDays,
    time: '1:00 PM',
    endTime: '2:30 PM',
    location: 'Recreation Room',
    createdBy: 'n1',
    createdAt: new Date(),
  },
  {
    id: '4',
    title: 'Family Visit - Sarah & Emily',
    description: 'Best time to visit: after lunch, before afternoon nap',
    type: 'family_visit',
    date: nextWeek,
    time: '1:00 PM',
    endTime: '3:00 PM',
    location: 'Room 214B or Garden Patio',
    patientMood: 'great',
    visitWindow: true,
    claimedBy: '1',
    claimedByName: 'Sarah',
    createdBy: '1',
    createdAt: new Date(),
  },
  {
    id: '5',
    title: 'Music Therapy',
    description: 'Group sing-along and music appreciation. Margaret loves the oldies!',
    type: 'facility_event',
    date: inTwoDays,
    time: '3:00 PM',
    endTime: '4:00 PM',
    location: 'Activity Center',
    createdBy: 'n1',
    createdAt: new Date(),
  },
  {
    id: '6',
    title: 'Open Visit Window',
    description: 'Grandma is usually in great spirits after PT. Perfect time to drop by!',
    type: 'family_visit',
    date: inFourDays,
    time: '3:00 PM',
    endTime: '5:00 PM',
    location: 'Room 214B',
    patientMood: 'good',
    visitWindow: true,
    createdBy: 'n1',
    createdAt: new Date(),
  },
]

export const demoVault: Vault = {
  insuranceCards: [
    {
      id: '1',
      name: 'Medicare Part A & B',
      memberId: '1EG4-TE5-MK72',
      groupNumber: 'N/A',
      notes: 'Primary insurance',
    },
    {
      id: '2',
      name: 'AARP Supplemental',
      memberId: 'SUP-789456123',
      groupNumber: 'AARP-2024',
      notes: 'Secondary coverage',
    },
  ],
  medications: [
    {
      id: '1',
      name: 'Lisinopril',
      dosage: '10mg',
      frequency: 'Once daily, morning',
      prescribedBy: 'Dr. Williams',
      notes: 'For blood pressure',
    },
    {
      id: '2',
      name: 'Metformin',
      dosage: '500mg',
      frequency: 'Twice daily with meals',
      prescribedBy: 'Dr. Chen',
      notes: 'For diabetes management',
    },
    {
      id: '3',
      name: 'Vitamin D3',
      dosage: '2000 IU',
      frequency: 'Once daily',
      notes: 'Supplement for bone health',
    },
    {
      id: '4',
      name: 'Acetaminophen',
      dosage: '500mg',
      frequency: 'As needed, max 4x daily',
      prescribedBy: 'Dr. Williams',
      notes: 'Post-surgery pain management',
    },
  ],
  providers: [
    {
      id: '1',
      name: 'Dr. James Williams',
      specialty: 'Orthopedic Surgeon',
      phone: '(555) 111-2222',
      address: 'Sunrise Medical Center, 123 Medical Dr',
    },
    {
      id: '2',
      name: 'Dr. Lisa Chen',
      specialty: 'Primary Care / Internist',
      phone: '(555) 333-4444',
      address: 'Family Health Clinic, 789 Oak Ave',
    },
    {
      id: '3',
      name: 'Dr. Michael Brown',
      specialty: 'Endocrinologist',
      phone: '(555) 555-6666',
      address: 'Diabetes Center, 321 Pine St',
    },
    {
      id: '4',
      name: 'PT Sarah Martinez',
      specialty: 'Physical Therapist',
      phone: '(555) 800-1240',
      address: 'Sunrise SNF, PT Department',
    },
  ],
  facilityInfo: {
    roomNumber: '214B',
    floor: '2nd Floor',
    wing: 'East Wing',
    facilityName: 'Sunrise Skilled Nursing Facility',
    facilityPhone: '(555) 800-1234',
    facilityAddress: '450 Sunrise Blvd, Salt Lake City, UT 84103',
    nurseStation: 'East Wing 2nd Floor Station - (555) 800-1235',
    visitingHours: 'Daily 9:00 AM - 8:00 PM',
    wifiNetwork: 'Sunrise-Guest',
    wifiPassword: 'Welcome2025',
    parkingInfo: 'Free visitor parking in Lot B, enter through East entrance',
  },
  documents: [
    {
      id: 'doc1',
      name: 'Advance Directive',
      category: 'legal',
      fileType: 'pdf',
      fileSize: 245000,
      uploadedBy: '1',
      uploadedByName: 'Sarah Johnson',
      uploadedAt: new Date('2025-11-15'),
      notes: 'Signed and notarized copy',
    },
    {
      id: 'doc2',
      name: 'Power of Attorney',
      category: 'legal',
      fileType: 'pdf',
      fileSize: 312000,
      uploadedBy: '1',
      uploadedByName: 'Sarah Johnson',
      uploadedAt: new Date('2025-11-15'),
      notes: 'Sarah Johnson designated as healthcare POA',
    },
    {
      id: 'doc3',
      name: 'DNR Order',
      category: 'medical',
      fileType: 'pdf',
      fileSize: 89000,
      uploadedBy: 'n1',
      uploadedByName: 'Nurse Rachel Kim',
      uploadedAt: new Date('2025-11-20'),
    },
    {
      id: 'doc4',
      name: 'Discharge Plan',
      category: 'medical',
      fileType: 'pdf',
      fileSize: 178000,
      uploadedBy: 'n1',
      uploadedByName: 'Nurse Rachel Kim',
      uploadedAt: new Date('2026-01-10'),
      notes: 'Preliminary discharge plan - target date TBD',
    },
    {
      id: 'doc5',
      name: 'Insurance EOB - January',
      category: 'insurance',
      fileType: 'pdf',
      fileSize: 423000,
      uploadedBy: '1',
      uploadedByName: 'Sarah Johnson',
      uploadedAt: new Date('2026-01-28'),
    },
  ],
}

export const demoLogEntries: LogEntry[] = [
  {
    id: '1',
    category: 'vitals',
    title: 'Morning Vitals Check',
    notes: 'Vitals within normal range. Patient resting comfortably.',
    enteredBy: 'n1',
    enteredByName: 'Nurse Rachel Kim',
    enteredByRole: 'nurse',
    createdAt: new Date(today.getTime() - 2 * 60 * 60 * 1000), // 2 hours ago
    vitals: {
      bloodPressureSystolic: 128,
      bloodPressureDiastolic: 78,
      heartRate: 72,
      temperature: 98.4,
      oxygenSaturation: 97,
      respiratoryRate: 16,
    },
    comments: [
      {
        id: 'lc1',
        authorId: '1',
        authorName: 'Sarah Johnson',
        content: 'Thanks for the update Rachel! Her BP looks much better than last week.',
        createdAt: new Date(today.getTime() - 1 * 60 * 60 * 1000),
      },
    ],
  },
  {
    id: '2',
    category: 'medication',
    title: 'Morning Medications Administered',
    notes: 'All morning meds given on schedule. No adverse reactions.',
    enteredBy: 'n1',
    enteredByName: 'Nurse Rachel Kim',
    enteredByRole: 'nurse',
    createdAt: new Date(today.getTime() - 4 * 60 * 60 * 1000),
    medicationLog: {
      medicationName: 'Lisinopril 10mg, Metformin 500mg, Vitamin D3 2000 IU',
      dosage: 'As prescribed',
      route: 'Oral',
      administeredBy: 'Rachel Kim, RN',
    },
    comments: [],
  },
  {
    id: '3',
    category: 'activity',
    title: 'Physical Therapy Session',
    notes: 'Walked 150 feet with walker. Improved hip range of motion. Patient in good spirits.',
    enteredBy: 'n2',
    enteredByName: 'CNA David Torres',
    enteredByRole: 'nurse',
    createdAt: new Date(yesterday.getTime() + 14 * 60 * 60 * 1000), // yesterday 2pm
    activityLog: {
      activityType: 'physical_therapy',
      description: 'Hip mobility exercises, gait training with walker, standing balance work',
      duration: 45,
      participation: 'active',
    },
    comments: [
      {
        id: 'lc2',
        authorId: '2',
        authorName: 'Michael Johnson',
        content: 'Great to hear she is making progress! Keep it up Mom!',
        createdAt: new Date(yesterday.getTime() + 18 * 60 * 60 * 1000),
      },
    ],
  },
  {
    id: '4',
    category: 'mood',
    title: 'Daily Mood & Wellness Check',
    notes: 'Margaret is in great spirits today. Chatting with roommate and watching her shows. Ate most of her lunch.',
    enteredBy: 'n2',
    enteredByName: 'CNA David Torres',
    enteredByRole: 'nurse',
    createdAt: new Date(today.getTime() - 3 * 60 * 60 * 1000),
    moodLog: {
      mood: 'happy',
      alertness: 'alert',
      appetite: 'good',
      painLevel: 3,
      notes: 'Slight hip discomfort but manageable. Declined pain medication.',
    },
    comments: [
      {
        id: 'lc3',
        authorId: '3',
        authorName: 'Emily Davis',
        content: 'So glad to hear Grandma is happy! I will try to visit this weekend.',
        createdAt: new Date(today.getTime() - 1.5 * 60 * 60 * 1000),
      },
    ],
  },
  {
    id: '5',
    category: 'incident',
    title: 'Minor Balance Issue During Transfer',
    notes: 'During bed-to-wheelchair transfer, patient lost balance briefly. Staff caught her immediately. No injury. Will monitor closely.',
    enteredBy: 'n1',
    enteredByName: 'Nurse Rachel Kim',
    enteredByRole: 'nurse',
    createdAt: twoDaysAgo,
    incidentLog: {
      incidentType: 'fall',
      severity: 'low',
      description: 'Patient lost balance during bed-to-wheelchair transfer. Staff present and prevented fall.',
      actionTaken: 'Caught patient immediately, no impact. Assessed for injury - none found. Updated care plan to ensure two-person assist for transfers.',
      physicianNotified: false,
      familyNotified: true,
    },
    comments: [
      {
        id: 'lc4',
        authorId: '1',
        authorName: 'Sarah Johnson',
        content: 'Thank you for letting us know and for the quick response. Please keep the two-person assist in place.',
        createdAt: new Date(twoDaysAgo.getTime() + 3 * 60 * 60 * 1000),
      },
    ],
  },
  {
    id: '6',
    category: 'vitals',
    title: 'Evening Vitals Check',
    notes: 'Blood pressure slightly elevated this evening. Will continue to monitor.',
    enteredBy: 'n1',
    enteredByName: 'Nurse Rachel Kim',
    enteredByRole: 'nurse',
    createdAt: new Date(yesterday.getTime() + 19 * 60 * 60 * 1000),
    vitals: {
      bloodPressureSystolic: 142,
      bloodPressureDiastolic: 88,
      heartRate: 76,
      temperature: 98.6,
      oxygenSaturation: 96,
    },
    comments: [],
  },
  {
    id: '7',
    category: 'activity',
    title: 'Participated in Bingo Social Hour',
    notes: 'Margaret joined the recreation room for bingo. Won two rounds! Very engaged and social with other residents.',
    enteredBy: 'n2',
    enteredByName: 'CNA David Torres',
    enteredByRole: 'nurse',
    createdAt: new Date(threeDaysAgo.getTime() + 14 * 60 * 60 * 1000),
    activityLog: {
      activityType: 'social',
      description: 'Community bingo game in recreation room',
      duration: 90,
      participation: 'active',
    },
    comments: [],
  },
  {
    id: '8',
    category: 'medication',
    title: 'Pain Medication Administered',
    notes: 'Patient requested pain relief after physical therapy. Given Acetaminophen as prescribed.',
    enteredBy: 'n1',
    enteredByName: 'Nurse Rachel Kim',
    enteredByRole: 'nurse',
    createdAt: new Date(yesterday.getTime() + 15 * 60 * 60 * 1000),
    medicationLog: {
      medicationName: 'Acetaminophen',
      dosage: '500mg',
      route: 'Oral',
      administeredBy: 'Rachel Kim, RN',
    },
    comments: [],
  },
]

export const demoPosts: FeedPost[] = [
  {
    id: '1',
    authorId: 'n2',
    authorName: 'CNA David Torres',
    authorInitials: 'DT',
    authorRole: 'nurse',
    content: 'Margaret had a wonderful afternoon in the garden today! She loved the fresh air and spent time looking at the flowers. She said it reminded her of her own garden at home.',
    postType: 'facility_moment',
    media: [
      { type: 'image', url: 'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=800&h=800&fit=crop' },
    ],
    location: 'Sunrise Garden Patio',
    likes: ['1', '2', '3'],
    comments: [
      {
        id: 'c1',
        authorId: '1',
        authorName: 'Sarah Johnson',
        content: 'This makes my heart so happy! She always loved her garden. Thank you for taking her outside!',
        createdAt: new Date(today.getTime() - 1 * 60 * 60 * 1000),
      },
      {
        id: 'c2',
        authorId: '3',
        authorName: 'Emily Davis',
        content: 'Grandma looks so peaceful! I am bringing her favorite flowers when I visit.',
        createdAt: new Date(today.getTime() - 0.5 * 60 * 60 * 1000),
      },
    ],
    createdAt: new Date(today.getTime() - 2 * 60 * 60 * 1000),
  },
  {
    id: '2',
    authorId: '1',
    authorName: 'Sarah Johnson',
    authorInitials: 'SJ',
    authorRole: 'family',
    content: 'Visited Mom today and she was in such great spirits! We looked through old photo albums together and she told me stories I had never heard before. The staff here is amazing.',
    postType: 'visit_recap',
    media: [
      { type: 'image', url: 'https://images.unsplash.com/photo-1545450660-3378a7f3a364?w=800&h=800&fit=crop' },
    ],
    likes: ['2', '3', 'n1'],
    comments: [
      {
        id: 'c3',
        authorId: '2',
        authorName: 'Michael Johnson',
        content: 'Wish I could have been there! I will visit this weekend for sure.',
        createdAt: new Date(yesterday.getTime() + 20 * 60 * 60 * 1000),
      },
    ],
    createdAt: new Date(yesterday.getTime() + 16 * 60 * 60 * 1000),
  },
  {
    id: '3',
    authorId: 'n1',
    authorName: 'Nurse Rachel Kim',
    authorInitials: 'RK',
    authorRole: 'nurse',
    content: 'Margaret hit a milestone today in physical therapy! She walked 150 feet with her walker, her longest distance yet since surgery. The PT team is very pleased with her progress.',
    postType: 'milestone',
    likes: ['1', '2', '3'],
    comments: [],
    createdAt: new Date(twoDaysAgo.getTime() + 15 * 60 * 60 * 1000),
    isPinned: true,
  },
  {
    id: '4',
    authorId: '3',
    authorName: 'Emily Davis',
    authorInitials: 'ED',
    authorRole: 'family',
    content: 'Brought Grandma her favorite cookies from the bakery downtown. She shared them with her roommate and the nurses. Classic Grandma!',
    postType: 'visit_recap',
    media: [
      { type: 'image', url: 'https://images.unsplash.com/photo-1504754524776-8f4f37790ca0?w=800&h=800&fit=crop' },
    ],
    location: 'Room 214B',
    likes: ['1', '2', 'n1', 'n2'],
    comments: [
      {
        id: 'c4',
        authorId: 'n1',
        authorName: 'Nurse Rachel Kim',
        content: 'Those cookies were delicious! Margaret was beaming when you visited.',
        createdAt: new Date(threeDaysAgo.getTime() + 18 * 60 * 60 * 1000),
      },
    ],
    createdAt: new Date(threeDaysAgo.getTime() + 15 * 60 * 60 * 1000),
  },
]

// Visits
const fourDaysAgo = new Date(today.getTime() - 4 * 24 * 60 * 60 * 1000)
const fiveDaysAgo = new Date(today.getTime() - 5 * 24 * 60 * 60 * 1000)
const sixDaysAgo = new Date(today.getTime() - 6 * 24 * 60 * 60 * 1000)

export const demoVisits: Visit[] = [
  {
    id: 'v1',
    visitorId: '1',
    visitorName: 'Sarah Johnson',
    visitorRelationship: 'Daughter',
    checkInTime: new Date(today.getTime() - 1 * 60 * 60 * 1000),
    // no checkOutTime = currently visiting
    mood: undefined,
    note: undefined,
  },
  {
    id: 'v2',
    visitorId: '3',
    visitorName: 'Emily Davis',
    visitorRelationship: 'Granddaughter',
    checkInTime: new Date(yesterday.getTime() + 15 * 60 * 60 * 1000),
    checkOutTime: new Date(yesterday.getTime() + 17.25 * 60 * 60 * 1000),
    duration: 135,
    mood: 'great',
    note: 'Did puzzles together, grandma loved it!',
  },
  {
    id: 'v3',
    visitorId: '2',
    visitorName: 'Michael Johnson',
    visitorRelationship: 'Son',
    checkInTime: new Date(twoDaysAgo.getTime() + 10 * 60 * 60 * 1000),
    checkOutTime: new Date(twoDaysAgo.getTime() + 11.5 * 60 * 60 * 1000),
    duration: 90,
    mood: 'good',
    note: 'Brought her favorite cookies',
  },
  {
    id: 'v4',
    visitorId: '1',
    visitorName: 'Sarah Johnson',
    visitorRelationship: 'Daughter',
    checkInTime: new Date(threeDaysAgo.getTime() + 13 * 60 * 60 * 1000),
    checkOutTime: new Date(threeDaysAgo.getTime() + 16 * 60 * 60 * 1000),
    duration: 180,
    mood: 'great',
    note: 'Great visit, she was very talkative',
  },
  {
    id: 'v5',
    visitorId: '3',
    visitorName: 'Emily Davis',
    visitorRelationship: 'Granddaughter',
    checkInTime: new Date(fiveDaysAgo.getTime() + 14 * 60 * 60 * 1000),
    checkOutTime: new Date(fiveDaysAgo.getTime() + 15.75 * 60 * 60 * 1000),
    duration: 105,
    mood: 'good',
    note: undefined,
  },
]

// Notifications
export const demoNotifications: Notification[] = [
  {
    id: 'notif1',
    type: 'incident',
    title: 'Incident Reported',
    message: 'Minor balance issue during transfer. No injury. Staff responded immediately.',
    sourceId: '5',
    sourceType: 'log_entry',
    createdAt: new Date(today.getTime() - 1 * 60 * 60 * 1000),
    readBy: [],
  },
  {
    id: 'notif2',
    type: 'vitals',
    title: 'Vitals Logged',
    message: 'Morning vitals: BP 128/78, HR 72, O2 97%. All within normal range.',
    sourceId: '1',
    sourceType: 'log_entry',
    createdAt: new Date(today.getTime() - 2 * 60 * 60 * 1000),
    readBy: [],
  },
  {
    id: 'notif3',
    type: 'mood',
    title: 'Great Mood Today',
    message: 'Margaret is happy and alert. Chatting with roommate and watching her shows.',
    sourceId: '4',
    sourceType: 'log_entry',
    createdAt: new Date(today.getTime() - 3 * 60 * 60 * 1000),
    readBy: [],
  },
  {
    id: 'notif4',
    type: 'visit',
    title: 'Emily Visited',
    message: 'Emily Davis visited for 2h 15m. Did puzzles together.',
    sourceId: 'v2',
    sourceType: 'visit',
    createdAt: new Date(yesterday.getTime() + 17.25 * 60 * 60 * 1000),
    readBy: ['1'],
  },
  {
    id: 'notif5',
    type: 'medication',
    title: 'Medications Administered',
    message: 'All evening meds administered on schedule. No adverse reactions.',
    sourceId: '8',
    sourceType: 'log_entry',
    createdAt: new Date(yesterday.getTime() + 15 * 60 * 60 * 1000),
    readBy: ['1'],
  },
  {
    id: 'notif6',
    type: 'vitals',
    title: 'BP Slightly Elevated',
    message: 'Evening vitals: BP 142/88. Slightly high. Monitoring closely.',
    sourceId: '6',
    sourceType: 'log_entry',
    createdAt: new Date(yesterday.getTime() + 19 * 60 * 60 * 1000),
    readBy: ['1'],
  },
  {
    id: 'notif7',
    type: 'document',
    title: 'Document Uploaded',
    message: 'Discharge Plan uploaded by Nurse Rachel Kim.',
    sourceId: 'doc4',
    sourceType: 'document',
    createdAt: new Date('2026-01-10'),
    readBy: ['1', '2', '3'],
  },
]

// Wellness data (past 7 days)
export const demoWellnessDays: WellnessDay[] = [
  {
    date: sixDaysAgo,
    overallScore: 7,
    moodAM: 'content',
    moodPM: 'happy',
    appetite: 'good',
    painLevel: 3,
    socialEngagement: 'active',
    therapySessions: 1,
    visitCount: 0,
  },
  {
    date: fiveDaysAgo,
    overallScore: 7.5,
    moodAM: 'happy',
    moodPM: 'content',
    appetite: 'good',
    painLevel: 2,
    socialEngagement: 'moderate',
    therapySessions: 0,
    visitCount: 1,
  },
  {
    date: fourDaysAgo,
    overallScore: 6.5,
    moodAM: 'content',
    moodPM: 'happy',
    appetite: 'fair',
    painLevel: 4,
    socialEngagement: 'active',
    therapySessions: 1,
    visitCount: 0,
  },
  {
    date: threeDaysAgo,
    overallScore: 8,
    moodAM: 'happy',
    moodPM: 'happy',
    appetite: 'good',
    painLevel: 2,
    socialEngagement: 'active',
    therapySessions: 1,
    visitCount: 1,
  },
  {
    date: twoDaysAgo,
    overallScore: 6,
    moodAM: 'neutral',
    moodPM: 'content',
    appetite: 'fair',
    painLevel: 3,
    socialEngagement: 'moderate',
    therapySessions: 0,
    visitCount: 1,
  },
  {
    date: yesterday,
    overallScore: 8.5,
    moodAM: 'content',
    moodPM: 'happy',
    appetite: 'good',
    painLevel: 2,
    socialEngagement: 'active',
    therapySessions: 1,
    visitCount: 1,
  },
  {
    date: today,
    overallScore: 8,
    moodAM: 'happy',
    moodPM: undefined, // not yet recorded
    appetite: 'good',
    painLevel: 3,
    socialEngagement: 'moderate',
    therapySessions: 0,
    visitCount: 1,
  },
]
