import { CareCircleMember, CalendarEvent, Vault, LogEntry, FeedPost, PatientInfo, Visit, Notification, WellnessDay } from '@/types'

// Patient: Kenji Clyde Shintaku
export const demoPatient: PatientInfo = {
  name: 'Kenji Clyde Shintaku',
  dateOfBirth: new Date('1956-12-29'),
  roomNumber: '114',
  facilityName: 'ABC Assisted Living',
  facilityPhone: '(111) 111-1111',
  facilityAddress: '1234 Main St',
  admissionDate: new Date('2026-01-01'),
  primaryDiagnosis: 'Recovering from intensive heart surgery',
  photoUrl: '/images/kenji-profile.jpg',
}

// Family + Staff members
export const demoMembers: CareCircleMember[] = [
  {
    id: '1',
    name: 'Toshio Shintaku',
    email: 'tshin@gmail.com',
    phone: '(111) 111-1111',
    role: 'primary',
    relationship: 'Brother (Healthcare POA)',
    joinedAt: new Date('2026-01-01'),
  },
  {
    id: 'a1',
    name: 'Mary Wilson',
    email: 'mwilson@abcfacility.com',
    phone: '(111) 111-1111',
    role: 'admin',
    relationship: 'Facility Administrator',
    joinedAt: new Date('2026-01-01'),
  },
  {
    id: 'n1',
    name: 'Jane Doe',
    email: 'jdoe@gmail.com',
    phone: '(111) 111-1111',
    role: 'nurse',
    relationship: 'Primary Nurse',
    joinedAt: new Date('2026-01-01'),
  },
  {
    id: 'n2',
    name: 'Robert Kim',
    email: 'rkim@abcfacility.com',
    phone: '(111) 222-3333',
    role: 'nurse',
    relationship: 'CNA',
    joinedAt: new Date('2026-01-01'),
  },
  {
    id: '2',
    name: 'Kainoa Shintaku',
    email: 'kshin@gmail.com',
    phone: '(111) 111-1111',
    role: 'family',
    relationship: 'Nephew',
    joinedAt: new Date('2026-01-02'),
  },
  {
    id: '3',
    name: 'Jackson Shintaku',
    email: 'jshin@gmail.com',
    phone: '(111) 111-1111',
    role: 'family',
    relationship: 'Nephew',
    joinedAt: new Date('2026-01-03'),
  },
]

const today = new Date()
const yesterday = new Date(today.getTime() - 1 * 24 * 60 * 60 * 1000)
const twoDaysAgo = new Date(today.getTime() - 2 * 24 * 60 * 60 * 1000)
const threeDaysAgo = new Date(today.getTime() - 3 * 24 * 60 * 60 * 1000)
const fourDaysAgo = new Date(today.getTime() - 4 * 24 * 60 * 60 * 1000)
const fiveDaysAgo = new Date(today.getTime() - 5 * 24 * 60 * 60 * 1000)
const sixDaysAgo = new Date(today.getTime() - 6 * 24 * 60 * 60 * 1000)
const inTwoDays = new Date(today.getTime() + 2 * 24 * 60 * 60 * 1000)
const inThreeDays = new Date(today.getTime() + 3 * 24 * 60 * 60 * 1000)
const inFourDays = new Date(today.getTime() + 4 * 24 * 60 * 60 * 1000)
const inFiveDays = new Date(today.getTime() + 5 * 24 * 60 * 60 * 1000)
const nextWeek = new Date(today.getTime() + 7 * 24 * 60 * 60 * 1000)
const inTenDays = new Date(today.getTime() + 10 * 24 * 60 * 60 * 1000)
const inTwoWeeks = new Date(today.getTime() + 14 * 24 * 60 * 60 * 1000)

export const demoEvents: CalendarEvent[] = [
  {
    id: '1',
    title: 'Cardiology Follow-up',
    description: 'Post-surgery heart check with Dr. Nakamura',
    type: 'doctor_visit',
    date: inTwoDays,
    time: '9:30 AM',
    location: 'On-site clinic, Room 102',
    patientMood: 'good',
    createdBy: 'n1',
    createdAt: new Date(),
  },
  {
    id: '2',
    title: 'Cardiac Rehabilitation Session',
    description: 'Supervised exercise and heart monitoring',
    type: 'therapy_session',
    date: today,
    time: '10:00 AM',
    endTime: '11:00 AM',
    location: 'Rehab Center, 1st Floor',
    patientMood: 'fair',
    createdBy: 'n1',
    createdAt: new Date(),
  },
  {
    id: '3',
    title: 'Echocardiogram',
    description: 'Routine post-operative heart imaging',
    type: 'doctor_visit',
    date: inFourDays,
    time: '11:00 AM',
    location: 'Imaging Center, 2nd Floor',
    createdBy: 'n1',
    createdAt: new Date(),
  },
  {
    id: '4',
    title: 'Family Visit - Toshio & Kainoa',
    description: 'Afternoon visit — Kenji is usually in good spirits after lunch',
    type: 'family_visit',
    date: nextWeek,
    time: '1:00 PM',
    endTime: '3:00 PM',
    location: 'Room 114 or Common Area',
    patientMood: 'great',
    visitWindow: true,
    claimedBy: '1',
    claimedByName: 'Toshio',
    createdBy: '1',
    createdAt: new Date(),
  },
  {
    id: '5',
    title: 'Blood Work & Labs',
    description: 'Routine blood panel to check cardiac enzymes and medication levels',
    type: 'doctor_visit',
    date: inThreeDays,
    time: '7:30 AM',
    location: 'Lab, 1st Floor',
    createdBy: 'n1',
    createdAt: new Date(),
  },
  {
    id: '6',
    title: 'Movie Night',
    description: 'Community movie screening in the recreation room',
    type: 'facility_event',
    date: inFiveDays,
    time: '6:30 PM',
    endTime: '8:30 PM',
    location: 'Recreation Room',
    createdBy: 'n1',
    createdAt: new Date(),
  },
  {
    id: '7',
    title: 'Physical Therapy Session',
    description: 'Light walking and mobility exercises for post-surgery recovery',
    type: 'therapy_session',
    date: inTwoDays,
    time: '2:00 PM',
    endTime: '2:45 PM',
    location: 'PT Room, 1st Floor',
    createdBy: 'n1',
    createdAt: new Date(),
  },
  {
    id: '8',
    title: 'Nutritionist Consultation',
    description: 'Heart-healthy diet planning and review',
    type: 'doctor_visit',
    date: inTenDays,
    time: '10:30 AM',
    location: 'Nutrition Office, Room 108',
    createdBy: 'n1',
    createdAt: new Date(),
  },
  {
    id: '9',
    title: 'Open Visit Window',
    description: 'Kenji is usually relaxed and in good spirits after rehab. Great time to drop by!',
    type: 'family_visit',
    date: inFourDays,
    time: '3:00 PM',
    endTime: '5:00 PM',
    location: 'Room 114',
    patientMood: 'good',
    visitWindow: true,
    createdBy: 'n1',
    createdAt: new Date(),
  },
  {
    id: '10',
    title: 'Medication Review with Pharmacist',
    description: 'Review of all current cardiac medications, dosages, and potential interactions',
    type: 'doctor_visit',
    date: inTwoWeeks,
    time: '1:30 PM',
    location: 'Pharmacy Office, 1st Floor',
    createdBy: 'n1',
    createdAt: new Date(),
  },
]

export const demoVault: Vault = {
  insuranceCards: [
    {
      id: '1',
      name: 'Medicare Part A & B',
      memberId: '1EG4-TE5-MK72',
      groupNumber: 'N/A',
      notes: 'Primary insurance',
    },
    {
      id: '2',
      name: 'HMSA Blue Cross',
      memberId: 'HI-456789123',
      groupNumber: 'HMSA-2026',
      notes: 'Secondary coverage',
    },
  ],
  medications: [
    {
      id: '1',
      name: 'Metoprolol',
      dosage: '50mg',
      frequency: 'Twice daily, morning and evening',
      prescribedBy: 'Dr. Nakamura',
      notes: 'Beta-blocker for heart rate and blood pressure control post-surgery',
    },
    {
      id: '2',
      name: 'Warfarin',
      dosage: '5mg',
      frequency: 'Once daily, evening',
      prescribedBy: 'Dr. Nakamura',
      notes: 'Blood thinner to prevent clots — requires regular INR monitoring',
    },
    {
      id: '3',
      name: 'Lisinopril',
      dosage: '10mg',
      frequency: 'Once daily, morning',
      prescribedBy: 'Dr. Nakamura',
      notes: 'ACE inhibitor for blood pressure and heart function',
    },
    {
      id: '4',
      name: 'Atorvastatin',
      dosage: '40mg',
      frequency: 'Once daily, evening',
      prescribedBy: 'Dr. Nakamura',
      notes: 'Statin for cholesterol management',
    },
    {
      id: '5',
      name: 'Aspirin',
      dosage: '81mg',
      frequency: 'Once daily, morning',
      prescribedBy: 'Dr. Nakamura',
      notes: 'Low-dose aspirin for cardiac protection',
    },
    {
      id: '6',
      name: 'Oxycodone',
      dosage: '5mg',
      frequency: 'Every 6 hours as needed',
      prescribedBy: 'Dr. Nakamura',
      notes: 'Post-surgical pain management — being tapered down',
    },
  ],
  providers: [
    {
      id: '1',
      name: 'Dr. Hiroshi Nakamura',
      specialty: 'Cardiothoracic Surgeon',
      phone: '(111) 222-3333',
      address: 'Heart & Vascular Center, 500 Medical Dr',
    },
    {
      id: '2',
      name: 'Dr. Amy Chen',
      specialty: 'Primary Care / Internist',
      phone: '(111) 333-4444',
      address: 'Family Health Clinic, 789 Oak Ave',
    },
    {
      id: '3',
      name: 'Dr. Robert Patel',
      specialty: 'Cardiologist',
      phone: '(111) 444-5555',
      address: 'Cardiology Associates, 321 Pine St',
    },
    {
      id: '4',
      name: 'PT Mark Thompson',
      specialty: 'Physical Therapist (Cardiac Rehab)',
      phone: '(111) 111-1112',
      address: 'ABC Assisted Living, Rehab Dept',
    },
  ],
  facilityInfo: {
    roomNumber: '114',
    floor: '1st Floor',
    wing: 'West Wing',
    facilityName: 'ABC Assisted Living',
    facilityPhone: '(111) 111-1111',
    facilityAddress: '1234 Main St',
    nurseStation: 'West Wing 1st Floor Station - (111) 111-1111',
    visitingHours: 'Daily 9:00 AM - 8:00 PM',
    wifiNetwork: 'ABC-Guest',
    wifiPassword: 'Welcome2026',
    parkingInfo: 'Free visitor parking in front lot, enter through main entrance',
  },
  documents: [
    {
      id: 'doc1',
      name: 'Advance Directive',
      category: 'legal',
      fileType: 'pdf',
      fileSize: 245000,
      uploadedBy: '1',
      uploadedByName: 'Toshio Shintaku',
      uploadedAt: new Date('2026-01-05'),
      notes: 'Signed and notarized copy',
    },
    {
      id: 'doc2',
      name: 'Power of Attorney',
      category: 'legal',
      fileType: 'pdf',
      fileSize: 312000,
      uploadedBy: '1',
      uploadedByName: 'Toshio Shintaku',
      uploadedAt: new Date('2026-01-05'),
      notes: 'Toshio Shintaku designated as healthcare POA',
    },
    {
      id: 'doc3',
      name: 'Heart Surgery Operative Report',
      category: 'medical',
      fileType: 'pdf',
      fileSize: 520000,
      uploadedBy: 'n1',
      uploadedByName: 'Jane Doe',
      uploadedAt: new Date('2026-01-02'),
      notes: 'Detailed surgical report from Dr. Nakamura',
    },
    {
      id: 'doc4',
      name: 'Cardiac Rehab Plan',
      category: 'medical',
      fileType: 'pdf',
      fileSize: 178000,
      uploadedBy: 'n1',
      uploadedByName: 'Jane Doe',
      uploadedAt: new Date('2026-01-15'),
      notes: 'Phased recovery plan — currently Phase 2',
    },
    {
      id: 'doc5',
      name: 'Insurance EOB - January',
      category: 'insurance',
      fileType: 'pdf',
      fileSize: 423000,
      uploadedBy: '1',
      uploadedByName: 'Toshio Shintaku',
      uploadedAt: new Date('2026-01-28'),
    },
  ],
}

// ── Care Log Entries (20 entries, heart surgery recovery) ──────────────────

export const demoLogEntries: LogEntry[] = [
  // 1 — Today: Morning Vitals
  {
    id: '1',
    category: 'vitals',
    title: 'Morning Vitals Check',
    notes: 'Vitals stable. Heart rate and BP within target post-surgery range. Patient resting comfortably.',
    enteredBy: 'n1',
    enteredByName: 'Jane Doe',
    enteredByRole: 'nurse',
    createdAt: new Date(today.getTime() - 2 * 60 * 60 * 1000),
    vitals: {
      bloodPressureSystolic: 122,
      bloodPressureDiastolic: 74,
      heartRate: 68,
      temperature: 98.2,
      oxygenSaturation: 97,
      respiratoryRate: 16,
    },
    comments: [
      {
        id: 'lc1',
        authorId: '1',
        authorName: 'Toshio Shintaku',
        content: 'Glad to see his numbers looking good. Thanks for the update!',
        createdAt: new Date(today.getTime() - 1 * 60 * 60 * 1000),
      },
    ],
  },
  // 2 — Today: Morning Medications
  {
    id: '2',
    category: 'medication',
    title: 'Morning Medications Administered',
    notes: 'All morning cardiac meds given on schedule. No adverse reactions observed.',
    enteredBy: 'n1',
    enteredByName: 'Jane Doe',
    enteredByRole: 'nurse',
    createdAt: new Date(today.getTime() - 4 * 60 * 60 * 1000),
    medicationLog: {
      medicationName: 'Metoprolol 50mg, Lisinopril 10mg, Aspirin 81mg, Atorvastatin 40mg',
      dosage: 'As prescribed',
      route: 'Oral',
      administeredBy: 'Jane Doe, RN',
    },
    comments: [],
  },
  // 3 — Today: Mood Check
  {
    id: '3',
    category: 'mood',
    title: 'Daily Mood & Wellness Check',
    notes: 'Kenji is in good spirits today. Chatting with staff and reading the newspaper. Ate most of breakfast.',
    enteredBy: 'n2',
    enteredByName: 'Robert Kim',
    enteredByRole: 'nurse',
    createdAt: new Date(today.getTime() - 3 * 60 * 60 * 1000),
    moodLog: {
      mood: 'happy',
      alertness: 'alert',
      appetite: 'good',
      painLevel: 3,
      notes: 'Mild chest soreness but manageable. Declined additional pain medication.',
    },
    comments: [
      {
        id: 'lc2',
        authorId: '2',
        authorName: 'Kainoa Shintaku',
        content: 'Happy to hear Uncle Kenji is doing well! Will try to visit this weekend.',
        createdAt: new Date(today.getTime() - 1.5 * 60 * 60 * 1000),
      },
    ],
  },
  // 4 — Yesterday: Cardiac Rehab
  {
    id: '4',
    category: 'activity',
    title: 'Cardiac Rehabilitation Session',
    notes: 'Completed 20 minutes on the recumbent bike at low intensity. Heart rate stayed in target zone. No chest pain or shortness of breath.',
    enteredBy: 'n1',
    enteredByName: 'Jane Doe',
    enteredByRole: 'nurse',
    createdAt: new Date(yesterday.getTime() + 11 * 60 * 60 * 1000),
    activityLog: {
      activityType: 'physical_therapy',
      description: 'Recumbent bike, light resistance training, monitored walking',
      duration: 45,
      participation: 'active',
    },
    comments: [
      {
        id: 'lc3',
        authorId: '3',
        authorName: 'Jackson Shintaku',
        content: 'Awesome progress Uncle Kenji! Keep going strong!',
        createdAt: new Date(yesterday.getTime() + 18 * 60 * 60 * 1000),
      },
    ],
  },
  // 5 — Yesterday: Evening Vitals
  {
    id: '5',
    category: 'vitals',
    title: 'Evening Vitals Check',
    notes: 'Blood pressure slightly elevated this evening. Will continue to monitor overnight.',
    enteredBy: 'n1',
    enteredByName: 'Jane Doe',
    enteredByRole: 'nurse',
    createdAt: new Date(yesterday.getTime() + 19 * 60 * 60 * 1000),
    vitals: {
      bloodPressureSystolic: 138,
      bloodPressureDiastolic: 84,
      heartRate: 74,
      temperature: 98.6,
      oxygenSaturation: 96,
    },
    comments: [],
  },
  // 6 — Yesterday: Pain Medication
  {
    id: '6',
    category: 'medication',
    title: 'Pain Medication Administered',
    notes: 'Patient reported increased chest soreness after rehab. Given Oxycodone as prescribed.',
    enteredBy: 'n1',
    enteredByName: 'Jane Doe',
    enteredByRole: 'nurse',
    createdAt: new Date(yesterday.getTime() + 15 * 60 * 60 * 1000),
    medicationLog: {
      medicationName: 'Oxycodone',
      dosage: '5mg',
      route: 'Oral',
      administeredBy: 'Jane Doe, RN',
    },
    comments: [],
  },
  // 7 — Yesterday: Mood
  {
    id: '7',
    category: 'mood',
    title: 'Afternoon Mood Check',
    notes: 'Kenji was a bit tired after rehab but still in decent spirits. Watched TV and napped in the afternoon.',
    enteredBy: 'n2',
    enteredByName: 'Robert Kim',
    enteredByRole: 'nurse',
    createdAt: new Date(yesterday.getTime() + 14 * 60 * 60 * 1000),
    moodLog: {
      mood: 'content',
      alertness: 'drowsy',
      appetite: 'fair',
      painLevel: 4,
      notes: 'Post-rehab fatigue. Ate about half of lunch.',
    },
    comments: [],
  },
  // 8 — 2 days ago: Morning Vitals
  {
    id: '8',
    category: 'vitals',
    title: 'Morning Vitals Check',
    notes: 'Vitals look great this morning. O2 sat improved from yesterday.',
    enteredBy: 'n1',
    enteredByName: 'Jane Doe',
    enteredByRole: 'nurse',
    createdAt: new Date(twoDaysAgo.getTime() + 8 * 60 * 60 * 1000),
    vitals: {
      bloodPressureSystolic: 120,
      bloodPressureDiastolic: 72,
      heartRate: 66,
      temperature: 98.4,
      oxygenSaturation: 98,
      respiratoryRate: 15,
    },
    comments: [],
  },
  // 9 — 2 days ago: Incident (arrhythmia episode)
  {
    id: '9',
    category: 'incident',
    title: 'Brief Arrhythmia Episode',
    notes: 'Telemetry detected a brief episode of atrial fibrillation lasting approximately 45 seconds. Patient was asymptomatic. Resolved on its own.',
    enteredBy: 'n1',
    enteredByName: 'Jane Doe',
    enteredByRole: 'nurse',
    createdAt: twoDaysAgo,
    incidentLog: {
      incidentType: 'condition_change',
      severity: 'moderate',
      description: 'Brief atrial fibrillation episode detected on telemetry monitor. Duration ~45 seconds. Patient was resting and asymptomatic.',
      actionTaken: 'Notified Dr. Nakamura. Increased monitoring frequency. ECG ordered for tomorrow. Vitals checked immediately — all stable.',
      physicianNotified: true,
      familyNotified: true,
    },
    comments: [
      {
        id: 'lc4',
        authorId: '1',
        authorName: 'Toshio Shintaku',
        content: 'Thank you for catching this and notifying the doctor immediately. Please keep us posted on the ECG results.',
        createdAt: new Date(twoDaysAgo.getTime() + 3 * 60 * 60 * 1000),
      },
    ],
  },
  // 10 — 2 days ago: Activity (Walking)
  {
    id: '10',
    category: 'activity',
    title: 'Hallway Walk',
    notes: 'Walked two laps around the west wing hallway with walker. Slow but steady pace. No shortness of breath.',
    enteredBy: 'n2',
    enteredByName: 'Robert Kim',
    enteredByRole: 'nurse',
    createdAt: new Date(twoDaysAgo.getTime() + 14 * 60 * 60 * 1000),
    activityLog: {
      activityType: 'walk',
      description: 'Supervised hallway walk with walker, 2 laps (~200 feet total)',
      duration: 15,
      participation: 'active',
    },
    comments: [],
  },
  // 11 — 3 days ago: Vitals
  {
    id: '11',
    category: 'vitals',
    title: 'Morning Vitals Check',
    notes: 'Heart rate slightly elevated. Patient reports mild anxiety about recovery timeline.',
    enteredBy: 'n1',
    enteredByName: 'Jane Doe',
    enteredByRole: 'nurse',
    createdAt: new Date(threeDaysAgo.getTime() + 8 * 60 * 60 * 1000),
    vitals: {
      bloodPressureSystolic: 130,
      bloodPressureDiastolic: 80,
      heartRate: 78,
      temperature: 98.3,
      oxygenSaturation: 96,
    },
    comments: [],
  },
  // 12 — 3 days ago: Medication (Evening Warfarin)
  {
    id: '12',
    category: 'medication',
    title: 'Evening Medications Administered',
    notes: 'Warfarin and Metoprolol given. INR check scheduled for tomorrow.',
    enteredBy: 'n1',
    enteredByName: 'Jane Doe',
    enteredByRole: 'nurse',
    createdAt: new Date(threeDaysAgo.getTime() + 19 * 60 * 60 * 1000),
    medicationLog: {
      medicationName: 'Warfarin 5mg, Metoprolol 50mg',
      dosage: 'As prescribed',
      route: 'Oral',
      administeredBy: 'Jane Doe, RN',
    },
    comments: [],
  },
  // 13 — 3 days ago: Mood
  {
    id: '13',
    category: 'mood',
    title: 'Daily Mood & Wellness Check',
    notes: 'Kenji expressed some frustration about the pace of recovery. Had a good talk with him about setting realistic goals. Spirits improved after family call.',
    enteredBy: 'n2',
    enteredByName: 'Robert Kim',
    enteredByRole: 'nurse',
    createdAt: new Date(threeDaysAgo.getTime() + 12 * 60 * 60 * 1000),
    moodLog: {
      mood: 'anxious',
      alertness: 'alert',
      appetite: 'fair',
      painLevel: 3,
      notes: 'Worried about recovery timeline. Mood improved after video call with nephews.',
    },
    comments: [
      {
        id: 'lc5',
        authorId: '2',
        authorName: 'Kainoa Shintaku',
        content: 'We called him right after seeing this. He seemed much better afterward. Thanks for looking out for him.',
        createdAt: new Date(threeDaysAgo.getTime() + 16 * 60 * 60 * 1000),
      },
    ],
  },
  // 14 — 3 days ago: Cardiac Rehab
  {
    id: '14',
    category: 'activity',
    title: 'Cardiac Rehabilitation Session',
    notes: 'Completed 15 minutes on recumbent bike and upper body stretches. Mild fatigue at end. Progressing well.',
    enteredBy: 'n1',
    enteredByName: 'Jane Doe',
    enteredByRole: 'nurse',
    createdAt: new Date(threeDaysAgo.getTime() + 10 * 60 * 60 * 1000),
    activityLog: {
      activityType: 'physical_therapy',
      description: 'Cardiac rehab — recumbent bike, upper body stretches, breathing exercises',
      duration: 40,
      participation: 'active',
    },
    comments: [],
  },
  // 15 — 4 days ago: Vitals
  {
    id: '15',
    category: 'vitals',
    title: 'Morning Vitals Check',
    notes: 'All vitals within normal ranges. Surgical incision healing well, no signs of infection.',
    enteredBy: 'n1',
    enteredByName: 'Jane Doe',
    enteredByRole: 'nurse',
    createdAt: new Date(fourDaysAgo.getTime() + 8 * 60 * 60 * 1000),
    vitals: {
      bloodPressureSystolic: 118,
      bloodPressureDiastolic: 70,
      heartRate: 64,
      temperature: 98.1,
      oxygenSaturation: 98,
      respiratoryRate: 14,
    },
    comments: [],
  },
  // 16 — 4 days ago: Activity (Social)
  {
    id: '16',
    category: 'activity',
    title: 'Participated in Card Game Social',
    notes: 'Kenji joined the common area card game. Played for over an hour and was laughing and chatting with other residents.',
    enteredBy: 'n2',
    enteredByName: 'Robert Kim',
    enteredByRole: 'nurse',
    createdAt: new Date(fourDaysAgo.getTime() + 14 * 60 * 60 * 1000),
    activityLog: {
      activityType: 'social',
      description: 'Card game in common area with other residents',
      duration: 75,
      participation: 'active',
    },
    comments: [],
  },
  // 17 — 5 days ago: Medication (Warfarin dose adjustment)
  {
    id: '17',
    category: 'medication',
    title: 'Warfarin Dose Adjustment',
    notes: 'INR came back at 3.2 (slightly above target). Dr. Nakamura reduced Warfarin to 4mg temporarily. Will recheck INR in 3 days.',
    enteredBy: 'n1',
    enteredByName: 'Jane Doe',
    enteredByRole: 'nurse',
    createdAt: new Date(fiveDaysAgo.getTime() + 16 * 60 * 60 * 1000),
    medicationLog: {
      medicationName: 'Warfarin',
      dosage: '4mg (adjusted from 5mg)',
      route: 'Oral',
      administeredBy: 'Jane Doe, RN',
    },
    comments: [
      {
        id: 'lc6',
        authorId: '1',
        authorName: 'Toshio Shintaku',
        content: 'Thanks for the heads up about the dose change. When will we know if 4mg is the right amount?',
        createdAt: new Date(fiveDaysAgo.getTime() + 18 * 60 * 60 * 1000),
      },
    ],
  },
  // 18 — 5 days ago: Mood
  {
    id: '18',
    category: 'mood',
    title: 'Daily Mood & Wellness Check',
    notes: 'Kenji in great spirits today. Told stories about growing up in Hawaii. Staff enjoyed listening.',
    enteredBy: 'n2',
    enteredByName: 'Robert Kim',
    enteredByRole: 'nurse',
    createdAt: new Date(fiveDaysAgo.getTime() + 12 * 60 * 60 * 1000),
    moodLog: {
      mood: 'happy',
      alertness: 'alert',
      appetite: 'good',
      painLevel: 2,
      notes: 'Very talkative and cheerful. Appetite has improved.',
    },
    comments: [],
  },
  // 19 — 6 days ago: Vitals
  {
    id: '19',
    category: 'vitals',
    title: 'Morning Vitals Check',
    notes: 'Stable vitals. Good overnight — slept well with no reported chest pain.',
    enteredBy: 'n1',
    enteredByName: 'Jane Doe',
    enteredByRole: 'nurse',
    createdAt: new Date(sixDaysAgo.getTime() + 8 * 60 * 60 * 1000),
    vitals: {
      bloodPressureSystolic: 124,
      bloodPressureDiastolic: 76,
      heartRate: 70,
      temperature: 98.5,
      oxygenSaturation: 97,
    },
    comments: [],
  },
  // 20 — 6 days ago: Incident (mild confusion)
  {
    id: '20',
    category: 'incident',
    title: 'Brief Post-Anesthesia Confusion',
    notes: 'Kenji was briefly disoriented upon waking from afternoon nap. Resolved within 10 minutes. Likely residual post-anesthesia effect.',
    enteredBy: 'n1',
    enteredByName: 'Jane Doe',
    enteredByRole: 'nurse',
    createdAt: new Date(sixDaysAgo.getTime() + 15 * 60 * 60 * 1000),
    incidentLog: {
      incidentType: 'condition_change',
      severity: 'low',
      description: 'Brief disorientation upon waking from nap. Patient was confused about location for approximately 10 minutes.',
      actionTaken: 'Reassured patient, checked vitals (all normal). Oriented him to time and place. Episode resolved. Noted in chart as likely post-anesthesia residual effect.',
      physicianNotified: false,
      familyNotified: true,
    },
    comments: [],
  },
]

// ── Feed Posts (placeholder — no photos yet) ───────────────────────────────

export const demoPosts: FeedPost[] = [
  {
    id: '1',
    authorId: 'n2',
    authorName: 'Robert Kim',
    authorInitials: 'RK',
    authorRole: 'nurse',
    content: 'Kenji had a wonderful morning today! He was up early, ate a full breakfast, and even cracked a few jokes with the staff. His recovery energy is inspiring.',
    postType: 'facility_moment',
    media: [
      { type: 'image', url: 'https://images.unsplash.com/photo-1559526324-593bc073d938?w=800&h=800&fit=crop' },
    ],
    location: 'ABC Assisted Living Dining Hall',
    likes: ['1', '2', '3'],
    comments: [
      {
        id: 'c1',
        authorId: '1',
        authorName: 'Toshio Shintaku',
        content: 'That sounds like my brother! He always knows how to make people laugh.',
        createdAt: new Date(today.getTime() - 1 * 60 * 60 * 1000),
      },
      {
        id: 'c2',
        authorId: '2',
        authorName: 'Kainoa Shintaku',
        content: 'Uncle Kenji always brightens the room. Glad to hear he is eating well!',
        createdAt: new Date(today.getTime() - 0.5 * 60 * 60 * 1000),
      },
    ],
    createdAt: new Date(today.getTime() - 2 * 60 * 60 * 1000),
  },
  {
    id: '2',
    authorId: '1',
    authorName: 'Toshio Shintaku',
    authorInitials: 'TS',
    authorRole: 'primary',
    content: 'Visited Kenji today and we looked through old family photos from Hawaii. He was so happy remembering the good times. The staff here takes such great care of him.',
    postType: 'visit_recap',
    media: [
      { type: 'image', url: 'https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=800&h=800&fit=crop' },
    ],
    likes: ['2', '3', 'n1'],
    comments: [
      {
        id: 'c3',
        authorId: '3',
        authorName: 'Jackson Shintaku',
        content: 'I love those old photos! Next time bring the album with the beach pictures.',
        createdAt: new Date(yesterday.getTime() + 20 * 60 * 60 * 1000),
      },
    ],
    createdAt: new Date(yesterday.getTime() + 16 * 60 * 60 * 1000),
  },
  {
    id: '3',
    authorId: 'n1',
    authorName: 'Jane Doe',
    authorInitials: 'JD',
    authorRole: 'nurse',
    content: 'Milestone! Kenji completed his first full cardiac rehab session today without needing to stop early. His endurance is improving week over week. The rehab team is very pleased.',
    postType: 'milestone',
    likes: ['1', '2', '3'],
    comments: [],
    createdAt: new Date(twoDaysAgo.getTime() + 15 * 60 * 60 * 1000),
    isPinned: true,
  },
  {
    id: '4',
    authorId: '2',
    authorName: 'Kainoa Shintaku',
    authorInitials: 'KS',
    authorRole: 'family',
    content: 'Brought Uncle Kenji some musubi and mochi from the Japanese market. He shared with the nurses and was grinning from ear to ear. Classic Uncle Kenji!',
    postType: 'visit_recap',
    media: [
      { type: 'image', url: 'https://images.unsplash.com/photo-1504754524776-8f4f37790ca0?w=800&h=800&fit=crop' },
    ],
    location: 'Room 114',
    likes: ['1', '3', 'n1', 'n2'],
    comments: [
      {
        id: 'c4',
        authorId: 'n1',
        authorName: 'Jane Doe',
        content: 'The musubi was so good! Kenji was absolutely beaming during your visit.',
        createdAt: new Date(threeDaysAgo.getTime() + 18 * 60 * 60 * 1000),
      },
    ],
    createdAt: new Date(threeDaysAgo.getTime() + 15 * 60 * 60 * 1000),
  },
]

// ── Visits ──────────────────────────────────────────────────────────────────

export const demoVisits: Visit[] = [
  {
    id: 'v1',
    visitorId: '1',
    visitorName: 'Toshio Shintaku',
    visitorRelationship: 'Brother',
    checkInTime: new Date(today.getTime() - 1 * 60 * 60 * 1000),
    // no checkOutTime = currently visiting
    mood: undefined,
    note: undefined,
  },
  {
    id: 'v2',
    visitorId: '2',
    visitorName: 'Kainoa Shintaku',
    visitorRelationship: 'Nephew',
    checkInTime: new Date(yesterday.getTime() + 15 * 60 * 60 * 1000),
    checkOutTime: new Date(yesterday.getTime() + 17 * 60 * 60 * 1000),
    duration: 120,
    mood: 'great',
    note: 'Brought food from the Japanese market. Uncle Kenji loved it!',
  },
  {
    id: 'v3',
    visitorId: '3',
    visitorName: 'Jackson Shintaku',
    visitorRelationship: 'Nephew',
    checkInTime: new Date(twoDaysAgo.getTime() + 10 * 60 * 60 * 1000),
    checkOutTime: new Date(twoDaysAgo.getTime() + 11.5 * 60 * 60 * 1000),
    duration: 90,
    mood: 'good',
    note: 'Watched sports together on TV',
  },
  {
    id: 'v4',
    visitorId: '1',
    visitorName: 'Toshio Shintaku',
    visitorRelationship: 'Brother',
    checkInTime: new Date(threeDaysAgo.getTime() + 13 * 60 * 60 * 1000),
    checkOutTime: new Date(threeDaysAgo.getTime() + 16 * 60 * 60 * 1000),
    duration: 180,
    mood: 'great',
    note: 'Looked through old family photo albums together',
  },
  {
    id: 'v5',
    visitorId: '2',
    visitorName: 'Kainoa Shintaku',
    visitorRelationship: 'Nephew',
    checkInTime: new Date(fiveDaysAgo.getTime() + 14 * 60 * 60 * 1000),
    checkOutTime: new Date(fiveDaysAgo.getTime() + 15.75 * 60 * 60 * 1000),
    duration: 105,
    mood: 'good',
    note: undefined,
  },
]

// ── Notifications ──────────────────────────────────────────────────────────

export const demoNotifications: Notification[] = [
  {
    id: 'notif1',
    type: 'incident',
    title: 'Arrhythmia Episode Detected',
    message: 'Brief atrial fibrillation episode. Patient asymptomatic. Dr. Nakamura notified.',
    sourceId: '9',
    sourceType: 'log_entry',
    createdAt: new Date(twoDaysAgo.getTime() + 1 * 60 * 60 * 1000),
    readBy: [],
  },
  {
    id: 'notif2',
    type: 'vitals',
    title: 'Vitals Logged',
    message: 'Morning vitals: BP 122/74, HR 68, O2 97%. All within target post-surgery range.',
    sourceId: '1',
    sourceType: 'log_entry',
    createdAt: new Date(today.getTime() - 2 * 60 * 60 * 1000),
    readBy: [],
  },
  {
    id: 'notif3',
    type: 'mood',
    title: 'Good Mood Today',
    message: 'Kenji is happy and alert. Chatting with staff and reading the newspaper.',
    sourceId: '3',
    sourceType: 'log_entry',
    createdAt: new Date(today.getTime() - 3 * 60 * 60 * 1000),
    readBy: [],
  },
  {
    id: 'notif4',
    type: 'visit',
    title: 'Kainoa Visited',
    message: 'Kainoa Shintaku visited for 2 hours. Brought food from the Japanese market.',
    sourceId: 'v2',
    sourceType: 'visit',
    createdAt: new Date(yesterday.getTime() + 17 * 60 * 60 * 1000),
    readBy: ['1'],
  },
  {
    id: 'notif5',
    type: 'medication',
    title: 'Warfarin Dose Adjusted',
    message: 'Warfarin reduced from 5mg to 4mg. INR was 3.2 (slightly above target). Will recheck in 3 days.',
    sourceId: '17',
    sourceType: 'log_entry',
    createdAt: new Date(fiveDaysAgo.getTime() + 16 * 60 * 60 * 1000),
    readBy: ['1'],
  },
  {
    id: 'notif6',
    type: 'vitals',
    title: 'BP Slightly Elevated',
    message: 'Evening vitals: BP 138/84. Slightly above target. Monitoring closely.',
    sourceId: '5',
    sourceType: 'log_entry',
    createdAt: new Date(yesterday.getTime() + 19 * 60 * 60 * 1000),
    readBy: ['1'],
  },
  {
    id: 'notif7',
    type: 'document',
    title: 'Document Uploaded',
    message: 'Cardiac Rehab Plan uploaded by Jane Doe.',
    sourceId: 'doc4',
    sourceType: 'document',
    createdAt: new Date('2026-01-15'),
    readBy: ['1', '2', '3'],
  },
]

// ── Wellness Data (past 7 days) ────────────────────────────────────────────

export const demoWellnessDays: WellnessDay[] = [
  {
    date: sixDaysAgo,
    overallScore: 6.5,
    moodAM: 'content',
    moodPM: 'neutral',
    appetite: 'fair',
    painLevel: 4,
    socialEngagement: 'minimal',
    therapySessions: 0,
    visitCount: 0,
  },
  {
    date: fiveDaysAgo,
    overallScore: 7.5,
    moodAM: 'happy',
    moodPM: 'content',
    appetite: 'good',
    painLevel: 2,
    socialEngagement: 'active',
    therapySessions: 0,
    visitCount: 1,
  },
  {
    date: fourDaysAgo,
    overallScore: 7,
    moodAM: 'content',
    moodPM: 'happy',
    appetite: 'good',
    painLevel: 3,
    socialEngagement: 'active',
    therapySessions: 1,
    visitCount: 0,
  },
  {
    date: threeDaysAgo,
    overallScore: 6,
    moodAM: 'anxious',
    moodPM: 'content',
    appetite: 'fair',
    painLevel: 3,
    socialEngagement: 'moderate',
    therapySessions: 1,
    visitCount: 1,
  },
  {
    date: twoDaysAgo,
    overallScore: 7,
    moodAM: 'content',
    moodPM: 'content',
    appetite: 'good',
    painLevel: 3,
    socialEngagement: 'active',
    therapySessions: 0,
    visitCount: 1,
  },
  {
    date: yesterday,
    overallScore: 7.5,
    moodAM: 'content',
    moodPM: 'content',
    appetite: 'fair',
    painLevel: 4,
    socialEngagement: 'moderate',
    therapySessions: 1,
    visitCount: 1,
  },
  {
    date: today,
    overallScore: 8,
    moodAM: 'happy',
    moodPM: undefined,
    appetite: 'good',
    painLevel: 3,
    socialEngagement: 'moderate',
    therapySessions: 0,
    visitCount: 1,
  },
]

export const demoGoals = [
  {
    id: 'g1',
    title: 'Regain Independent Walking',
    category: 'Mobility',
    targetDate: 'Apr 15',
    progressPercent: 65,
    description: 'Walk 50ft unassisted',
    milestones: ['Walk with walker 20ft', 'Walk with minimal assist 30ft', 'Independent 50ft walk'],
  },
  {
    id: 'g2',
    title: 'Improve Nutritional Intake',
    category: 'Nutrition',
    targetDate: 'Mar 30',
    progressPercent: 80,
    description: 'Achieve 80% meal completion consistently',
    milestones: ['50% meal completion', '70% meal completion', '80% meal completion'],
  },
  {
    id: 'g3',
    title: 'Reduce Pain Levels',
    category: 'Comfort',
    targetDate: 'Apr 1',
    progressPercent: 50,
    description: 'Maintain pain score below 3/10',
    milestones: ['Pain management plan in place', 'Average pain 5/10', 'Average pain 3/10'],
  },
  {
    id: 'g4',
    title: 'Restore Upper Body Strength',
    category: 'Therapy',
    targetDate: 'May 1',
    progressPercent: 40,
    description: 'Complete OT strength exercises independently',
    milestones: ['Assisted exercises 3x/week', 'Partial independent exercises', 'Full independent exercises'],
  },
]

// ─── Resident Directory ──────────────────────────────────────────────────────

export interface ResidentSnapshot {
  id: string
  name: string
  roomNumber: string
  primaryDiagnosis: string
  admissionDate: Date
  dateOfBirth: Date
  lastVitals: { bp: string; heartRate: number; o2: number; recordedAt: Date }
  currentMood: 'great' | 'good' | 'fair' | 'poor'
  status: 'active' | 'discharged'
}

export const demoAllResidents: ResidentSnapshot[] = [
  {
    id: '00000000-0000-0000-0000-000000000001',
    name: 'Kenji Clyde Shintaku',
    roomNumber: '114',
    primaryDiagnosis: 'Recovering from intensive heart surgery',
    admissionDate: new Date('2026-01-01'),
    dateOfBirth: new Date('1956-12-29'),
    lastVitals: { bp: '118/76', heartRate: 68, o2: 97, recordedAt: new Date(Date.now() - 2 * 60 * 60 * 1000) },
    currentMood: 'good',
    status: 'active',
  },
  {
    id: 'demo-patient-2',
    name: 'Margaret Chen',
    roomNumber: '206',
    primaryDiagnosis: "Alzheimer's Disease — Stage 2",
    admissionDate: new Date('2025-09-15'),
    dateOfBirth: new Date('1942-03-11'),
    lastVitals: { bp: '132/84', heartRate: 74, o2: 96, recordedAt: new Date(Date.now() - 4 * 60 * 60 * 1000) },
    currentMood: 'fair',
    status: 'active',
  },
  {
    id: 'demo-patient-3',
    name: 'Robert Johnson',
    roomNumber: '118',
    primaryDiagnosis: 'Post-Hip Replacement Recovery',
    admissionDate: new Date('2026-02-10'),
    dateOfBirth: new Date('1950-07-22'),
    lastVitals: { bp: '124/80', heartRate: 72, o2: 98, recordedAt: new Date(Date.now() - 1 * 60 * 60 * 1000) },
    currentMood: 'great',
    status: 'active',
  },
  {
    id: 'demo-patient-4',
    name: 'Dorothy Williams',
    roomNumber: '302',
    primaryDiagnosis: 'Type 2 Diabetes & Hypertension',
    admissionDate: new Date('2025-11-03'),
    dateOfBirth: new Date('1948-11-30'),
    lastVitals: { bp: '142/90', heartRate: 80, o2: 95, recordedAt: new Date(Date.now() - 6 * 60 * 60 * 1000) },
    currentMood: 'good',
    status: 'active',
  },
]
