'use client'

import { useState } from 'react'
import {
  Download,
  FileText,
  Table,
  Share2,
  X,
  Check,
  Copy,
  QrCode,
  Mail,
  Link
} from 'lucide-react'
import { Vault, Incident, CalendarEvent } from '@/types'

interface ExportModalProps {
  isOpen: boolean
  onClose: () => void
  vault: Vault
  incidents: Incident[]
  events: CalendarEvent[]
}

export default function ExportModal({
  isOpen,
  onClose,
  vault,
  incidents,
  events,
}: ExportModalProps) {
  const [activeTab, setActiveTab] = useState<'export' | 'share'>('export')
  const [copied, setCopied] = useState(false)
  const [exportStatus, setExportStatus] = useState<string | null>(null)

  if (!isOpen) return null

  const shareLink = `https://gather.app/share/${Math.random().toString(36).substring(7)}`

  const copyLink = () => {
    navigator.clipboard.writeText(shareLink)
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }

  const exportMedicationsCSV = () => {
    const headers = ['Medication', 'Dosage', 'Frequency', 'Prescribed By', 'Notes']
    const rows = vault.medications.map((med) => [
      med.name,
      med.dosage,
      med.frequency,
      med.prescribedBy || '',
      med.notes || '',
    ])

    const csv = [headers, ...rows]
      .map((row) => row.map((cell) => `"${cell}"`).join(','))
      .join('\n')

    downloadFile(csv, 'medications.csv', 'text/csv')
    setExportStatus('Medications exported successfully!')
    setTimeout(() => setExportStatus(null), 3000)
  }

  const exportIncidentsCSV = () => {
    const headers = ['Date', 'Title', 'Description', 'Severity', 'Reported By', 'Tags']
    const rows = incidents.map((inc) => [
      new Date(inc.createdAt).toLocaleDateString(),
      inc.title,
      inc.description,
      inc.severity,
      inc.reportedByName,
      inc.tags?.join('; ') || '',
    ])

    const csv = [headers, ...rows]
      .map((row) => row.map((cell) => `"${cell}"`).join(','))
      .join('\n')

    downloadFile(csv, 'health-updates.csv', 'text/csv')
    setExportStatus('Health updates exported successfully!')
    setTimeout(() => setExportStatus(null), 3000)
  }

  const exportCareSummaryPDF = () => {
    // Generate a simple text-based summary that can be copied/printed
    const summary = generateCareSummary()

    // Open in new window for printing
    const printWindow = window.open('', '_blank')
    if (printWindow) {
      printWindow.document.write(`
        <!DOCTYPE html>
        <html>
        <head>
          <title>Care Summary - Gather</title>
          <style>
            body { font-family: 'Nunito', system-ui, sans-serif; padding: 40px; max-width: 800px; margin: 0 auto; }
            h1 { color: #e07a5f; border-bottom: 2px solid #e07a5f; padding-bottom: 10px; }
            h2 { color: #3d405b; margin-top: 30px; }
            .section { margin-bottom: 20px; }
            table { width: 100%; border-collapse: collapse; margin-top: 10px; }
            th, td { padding: 8px; text-align: left; border-bottom: 1px solid #fdf3de; }
            th { background: #fef9ef; color: #3d405b; }
            .footer { margin-top: 40px; text-align: center; color: #81b29a; font-size: 14px; }
            @media print { .no-print { display: none; } }
          </style>
        </head>
        <body>
          ${summary}
          <div class="footer">
            Generated by Gather on ${new Date().toLocaleDateString()}
          </div>
          <div class="no-print" style="margin-top: 20px; text-align: center;">
            <button onclick="window.print()" style="padding: 10px 20px; background: #e07a5f; color: white; border: none; border-radius: 10px; cursor: pointer;">
              Print / Save as PDF
            </button>
          </div>
        </body>
        </html>
      `)
      printWindow.document.close()
    }
    setExportStatus('Care summary opened in new window!')
    setTimeout(() => setExportStatus(null), 3000)
  }

  const generateCareSummary = () => {
    let html = '<h1>Care Summary</h1>'

    // Medications
    html += '<div class="section"><h2>Current Medications</h2>'
    if (vault.medications.length > 0) {
      html += '<table><tr><th>Medication</th><th>Dosage</th><th>Frequency</th></tr>'
      vault.medications.forEach((med) => {
        html += `<tr><td>${med.name}</td><td>${med.dosage}</td><td>${med.frequency}</td></tr>`
      })
      html += '</table>'
    } else {
      html += '<p>No medications recorded.</p>'
    }
    html += '</div>'

    // Insurance
    html += '<div class="section"><h2>Insurance Information</h2>'
    if (vault.insuranceCards.length > 0) {
      vault.insuranceCards.forEach((card) => {
        html += `<p><strong>${card.name}</strong>: Member ID ${card.memberId}${card.groupNumber ? `, Group #${card.groupNumber}` : ''}</p>`
      })
    } else {
      html += '<p>No insurance information recorded.</p>'
    }
    html += '</div>'

    // Providers
    html += '<div class="section"><h2>Healthcare Providers</h2>'
    if (vault.providers.length > 0) {
      html += '<table><tr><th>Provider</th><th>Specialty</th><th>Phone</th></tr>'
      vault.providers.forEach((provider) => {
        html += `<tr><td>${provider.name}</td><td>${provider.specialty}</td><td>${provider.phone}</td></tr>`
      })
      html += '</table>'
    } else {
      html += '<p>No providers recorded.</p>'
    }
    html += '</div>'

    // Recent Health Updates
    html += '<div class="section"><h2>Recent Health Updates</h2>'
    const recentIncidents = incidents.slice(0, 5)
    if (recentIncidents.length > 0) {
      recentIncidents.forEach((inc) => {
        html += `<p><strong>${new Date(inc.createdAt).toLocaleDateString()}</strong> - ${inc.title}: ${inc.description}</p>`
      })
    } else {
      html += '<p>No health updates recorded.</p>'
    }
    html += '</div>'

    return html
  }

  const downloadFile = (content: string, filename: string, type: string) => {
    const blob = new Blob([content], { type })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = filename
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    URL.revokeObjectURL(url)
  }

  return (
    <div className="fixed inset-0 bg-warm-900 bg-opacity-50 flex items-center justify-center p-4 z-50">
      <div className="bg-white rounded-3xl max-w-lg w-full p-6 shadow-xl">
        <div className="flex items-center justify-between mb-6">
          <h3 className="text-xl font-semibold text-warm-900">Export & Share</h3>
          <button
            onClick={onClose}
            className="p-2 hover:bg-cream-100 rounded-xl transition-colors"
          >
            <X className="h-5 w-5 text-warm-500" />
          </button>
        </div>

        {/* Tabs */}
        <div className="flex gap-2 mb-6">
          <button
            onClick={() => setActiveTab('export')}
            className={`flex-1 flex items-center justify-center gap-2 px-4 py-2.5 rounded-xl text-sm font-medium transition-all duration-200 ${
              activeTab === 'export'
                ? 'bg-primary-100 text-primary-700'
                : 'text-warm-600 hover:bg-cream-100'
            }`}
          >
            <Download className="h-4 w-4" />
            Export
          </button>
          <button
            onClick={() => setActiveTab('share')}
            className={`flex-1 flex items-center justify-center gap-2 px-4 py-2.5 rounded-xl text-sm font-medium transition-all duration-200 ${
              activeTab === 'share'
                ? 'bg-primary-100 text-primary-700'
                : 'text-warm-600 hover:bg-cream-100'
            }`}
          >
            <Share2 className="h-4 w-4" />
            Share
          </button>
        </div>

        {/* Status Message */}
        {exportStatus && (
          <div className="mb-4 p-3 bg-sage-50 text-sage-700 rounded-xl flex items-center gap-2">
            <Check className="h-4 w-4" />
            {exportStatus}
          </div>
        )}

        {/* Export Tab */}
        {activeTab === 'export' && (
          <div className="space-y-3">
            <button
              onClick={exportCareSummaryPDF}
              className="w-full flex items-center gap-4 p-4 border border-cream-200 rounded-2xl hover:border-primary-200 hover:bg-cream-50 transition-all duration-200 text-left"
            >
              <div className="p-3 bg-primary-100 rounded-xl">
                <FileText className="h-6 w-6 text-primary-600" />
              </div>
              <div>
                <h4 className="font-medium text-warm-900">Care Summary</h4>
                <p className="text-sm text-warm-500">
                  Complete overview with medications, providers, and updates
                </p>
              </div>
            </button>

            <button
              onClick={exportMedicationsCSV}
              className="w-full flex items-center gap-4 p-4 border border-cream-200 rounded-2xl hover:border-primary-200 hover:bg-cream-50 transition-all duration-200 text-left"
            >
              <div className="p-3 bg-sage-100 rounded-xl">
                <Table className="h-6 w-6 text-sage-600" />
              </div>
              <div>
                <h4 className="font-medium text-warm-900">Medications (CSV)</h4>
                <p className="text-sm text-warm-500">
                  Export medication list for doctor visits
                </p>
              </div>
            </button>

            <button
              onClick={exportIncidentsCSV}
              className="w-full flex items-center gap-4 p-4 border border-cream-200 rounded-2xl hover:border-primary-200 hover:bg-cream-50 transition-all duration-200 text-left"
            >
              <div className="p-3 bg-terracotta-100 rounded-xl">
                <Table className="h-6 w-6 text-terracotta-600" />
              </div>
              <div>
                <h4 className="font-medium text-warm-900">Health Updates (CSV)</h4>
                <p className="text-sm text-warm-500">
                  Export incident history for records
                </p>
              </div>
            </button>
          </div>
        )}

        {/* Share Tab */}
        {activeTab === 'share' && (
          <div className="space-y-4">
            <div>
              <label className="block text-sm font-medium text-warm-700 mb-2">
                Share Link (View Only)
              </label>
              <div className="flex gap-2">
                <input
                  type="text"
                  value={shareLink}
                  readOnly
                  className="flex-1 px-3 py-2.5 bg-cream-50 border border-cream-200 rounded-xl text-sm text-warm-600"
                />
                <button
                  onClick={copyLink}
                  className="px-4 py-2.5 bg-primary-100 text-primary-700 rounded-xl hover:bg-primary-200 transition-colors"
                >
                  {copied ? <Check className="h-5 w-5" /> : <Copy className="h-5 w-5" />}
                </button>
              </div>
            </div>

            <div className="grid grid-cols-2 gap-3">
              <button
                onClick={() => window.open(`mailto:?subject=Gather Care Circle&body=Join our care circle: ${encodeURIComponent(shareLink)}`)}
                className="flex items-center justify-center gap-2 p-4 border border-cream-200 rounded-2xl hover:border-primary-200 hover:bg-cream-50 transition-all duration-200"
              >
                <Mail className="h-5 w-5 text-warm-600" />
                <span className="font-medium text-warm-700">Email</span>
              </button>

              <button
                onClick={copyLink}
                className="flex items-center justify-center gap-2 p-4 border border-cream-200 rounded-2xl hover:border-primary-200 hover:bg-cream-50 transition-all duration-200"
              >
                <Link className="h-5 w-5 text-warm-600" />
                <span className="font-medium text-warm-700">Copy Link</span>
              </button>
            </div>

            <div className="p-4 bg-cream-50 rounded-2xl">
              <div className="flex items-start gap-3">
                <QrCode className="h-5 w-5 text-warm-500 mt-0.5" />
                <div>
                  <h4 className="font-medium text-warm-700">QR Code Access</h4>
                  <p className="text-sm text-warm-500 mt-1">
                    In the full version, scan with any phone camera for instant mobile access.
                  </p>
                </div>
              </div>
            </div>
          </div>
        )}

        <button
          onClick={onClose}
          className="w-full mt-6 px-4 py-2.5 border border-cream-200 text-warm-700 rounded-xl hover:bg-cream-50 transition-colors"
        >
          Close
        </button>
      </div>
    </div>
  )
}
