'use client'

import { useState } from 'react'
import {
  Download,
  FileText,
  Table,
  X,
  Check,
} from 'lucide-react'
import { Vault, LogEntry, CalendarEvent } from '@/types'
import { escapeHtml } from '@/lib/utils'

/** Sanitize a CSV cell: escape double-quotes and prefix formula characters */
function csvSafe(value: string): string {
  let escaped = value.replace(/"/g, '""')
  // Prevent CSV formula injection in Excel
  if (/^[=+\-@\t\r]/.test(escaped)) {
    escaped = `'${escaped}`
  }
  return `"${escaped}"`
}

interface ExportModalProps {
  isOpen: boolean
  onClose: () => void
  vault: Vault
  logEntries: LogEntry[]
  events: CalendarEvent[]
}

export default function ExportModal({
  isOpen,
  onClose,
  vault,
  logEntries,
  events,
}: ExportModalProps) {
  const [exportStatus, setExportStatus] = useState<string | null>(null)

  if (!isOpen) return null

  const exportMedicationsCSV = () => {
    const headers = ['Medication', 'Dosage', 'Frequency', 'Prescribed By', 'Notes']
    const rows = vault.medications.map((med) => [
      med.name, med.dosage, med.frequency, med.prescribedBy || '', med.notes || '',
    ])
    const csv = [headers.map(csvSafe), ...rows.map((row) => row.map(csvSafe))].map((r) => r.join(',')).join('\n')
    downloadFile(csv, 'medications.csv', 'text/csv')
    setExportStatus('Medications exported successfully!')
    setTimeout(() => setExportStatus(null), 3000)
  }

  const exportLogCSV = () => {
    const headers = ['Date', 'Category', 'Title', 'Notes', 'Entered By']
    const rows = logEntries.map((entry) => [
      new Date(entry.createdAt).toLocaleDateString(),
      entry.category,
      entry.title,
      entry.notes || '',
      entry.enteredByName,
    ])
    const csv = [headers.map(csvSafe), ...rows.map((row) => row.map(csvSafe))].map((r) => r.join(',')).join('\n')
    downloadFile(csv, 'care-log.csv', 'text/csv')
    setExportStatus('Care log exported successfully!')
    setTimeout(() => setExportStatus(null), 3000)
  }

  const exportCareSummaryPDF = () => {
    const summary = generateCareSummary()
    const printWindow = window.open('', '_blank')
    if (printWindow) {
      printWindow.document.write(`
        <!DOCTYPE html>
        <html>
        <head>
          <title>Care Summary - CareBridge Connect</title>
          <style>
            body { font-family: 'Outfit', system-ui, sans-serif; padding: 40px; max-width: 800px; margin: 0 auto; }
            h1 { color: #7c3aed; border-bottom: 2px solid #7c3aed; padding-bottom: 10px; }
            h2 { color: #1e293b; margin-top: 30px; }
            .section { margin-bottom: 20px; }
            table { width: 100%; border-collapse: collapse; margin-top: 10px; }
            th, td { padding: 8px; text-align: left; border-bottom: 1px solid #e2e8f0; }
            th { background: #f8fafc; color: #334155; }
            .footer { margin-top: 40px; text-align: center; color: #94a3b8; font-size: 14px; }
            @media print { .no-print { display: none; } }
          </style>
        </head>
        <body>
          ${summary}
          <div class="footer">Generated by CareBridge Connect on ${new Date().toLocaleDateString()}</div>
          <div class="no-print" style="margin-top: 20px; text-align: center;">
            <button onclick="window.print()" style="padding: 10px 20px; background: #7c3aed; color: white; border: none; border-radius: 10px; cursor: pointer;">
              Print / Save as PDF
            </button>
          </div>
        </body>
        </html>
      `)
      printWindow.document.close()
    }
    setExportStatus('Care summary opened in new window!')
    setTimeout(() => setExportStatus(null), 3000)
  }

  const generateCareSummary = () => {
    const e = escapeHtml // alias for readability
    let html = '<h1>Care Summary</h1>'
    html += `<p><strong>Facility:</strong> ${e(vault.facilityInfo.facilityName)} | <strong>Room:</strong> ${e(vault.facilityInfo.roomNumber)}</p>`

    html += '<div class="section"><h2>Current Medications</h2>'
    if (vault.medications.length > 0) {
      html += '<table><tr><th>Medication</th><th>Dosage</th><th>Frequency</th></tr>'
      vault.medications.forEach((med) => {
        html += `<tr><td>${e(med.name)}</td><td>${e(med.dosage)}</td><td>${e(med.frequency)}</td></tr>`
      })
      html += '</table>'
    } else {
      html += '<p>No medications recorded.</p>'
    }
    html += '</div>'

    html += '<div class="section"><h2>Insurance Information</h2>'
    vault.insuranceCards.forEach((card) => {
      html += `<p><strong>${e(card.name)}</strong>: Member ID ${e(card.memberId)}${card.groupNumber ? `, Group #${e(card.groupNumber)}` : ''}</p>`
    })
    html += '</div>'

    html += '<div class="section"><h2>Care Team</h2>'
    if (vault.providers.length > 0) {
      html += '<table><tr><th>Provider</th><th>Specialty</th><th>Phone</th></tr>'
      vault.providers.forEach((provider) => {
        html += `<tr><td>${e(provider.name)}</td><td>${e(provider.specialty)}</td><td>${e(provider.phone)}</td></tr>`
      })
      html += '</table>'
    }
    html += '</div>'

    html += '<div class="section"><h2>Recent Care Log Entries</h2>'
    const recentEntries = logEntries.slice(0, 10)
    if (recentEntries.length > 0) {
      recentEntries.forEach((entry) => {
        html += `<p><strong>${new Date(entry.createdAt).toLocaleDateString()}</strong> [${e(entry.category)}] - ${e(entry.title)}: ${e(entry.notes || '')}</p>`
      })
    }
    html += '</div>'

    return html
  }

  const downloadFile = (content: string, filename: string, type: string) => {
    const blob = new Blob([content], { type })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = filename
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    URL.revokeObjectURL(url)
  }

  return (
    <div className="fixed inset-0 bg-navy-900/40 backdrop-blur-sm flex items-center justify-center p-4 z-50 animate-fade-in">
      <div className="bg-white rounded-3xl max-w-lg w-full p-6 shadow-glass-lg animate-scale-in">
        <div className="flex items-center justify-between mb-6">
          <h3 className="text-xl font-bold text-navy-900">Export & Share</h3>
          <button onClick={onClose} className="p-2 hover:bg-cream-100 rounded-xl transition-colors">
            <X className="h-5 w-5 text-navy-500" />
          </button>
        </div>

        <div className="flex gap-2 mb-6">
          <div className="flex-1 flex items-center justify-center gap-2 px-4 py-2.5 rounded-xl text-sm font-medium bg-primary-100 text-primary-700">
            <Download className="h-4 w-4" /> Export Data
          </div>
        </div>

        {exportStatus && (
          <div className="mb-4 p-3 bg-mint-50 text-mint-700 rounded-xl flex items-center gap-2">
            <Check className="h-4 w-4" /> {exportStatus}
          </div>
        )}

        <div className="space-y-3">
            <button onClick={exportCareSummaryPDF}
              className="w-full flex items-center gap-4 p-4 border border-primary-100 rounded-2xl hover:border-primary-300 hover:bg-cream-50 transition-all duration-200 text-left">
              <div className="p-3 bg-primary-100 rounded-xl">
                <FileText className="h-6 w-6 text-primary-600" />
              </div>
              <div>
                <h4 className="font-medium text-navy-900">Care Summary</h4>
                <p className="text-sm text-navy-500">Complete overview with medications, providers, and log entries</p>
              </div>
            </button>
            <button onClick={exportMedicationsCSV}
              className="w-full flex items-center gap-4 p-4 border border-primary-100 rounded-2xl hover:border-primary-300 hover:bg-cream-50 transition-all duration-200 text-left">
              <div className="p-3 bg-mint-100 rounded-xl">
                <Table className="h-6 w-6 text-mint-600" />
              </div>
              <div>
                <h4 className="font-medium text-navy-900">Medications (CSV)</h4>
                <p className="text-sm text-navy-500">Export medication list for doctor visits</p>
              </div>
            </button>
            <button onClick={exportLogCSV}
              className="w-full flex items-center gap-4 p-4 border border-primary-100 rounded-2xl hover:border-primary-300 hover:bg-cream-50 transition-all duration-200 text-left">
              <div className="p-3 bg-accent-100 rounded-xl">
                <Table className="h-6 w-6 text-accent-600" />
              </div>
              <div>
                <h4 className="font-medium text-navy-900">Care Log (CSV)</h4>
                <p className="text-sm text-navy-500">Export daily care log history</p>
              </div>
            </button>
          </div>

        <button onClick={onClose}
          className="w-full mt-6 px-4 py-2.5 border border-primary-200 text-navy-700 rounded-xl hover:bg-cream-50 transition-colors">
          Close
        </button>
      </div>
    </div>
  )
}
